### ISSUE TITLE
Unable to add additional flags when running as Gitlab Service

### ISSUE THREAD

**Issue by coleve27** [saucelabs/sauce-connect-docker#11]
In order to add additional flags when running as a [Gitlab Service](https://docs.gitlab.com/ee/ci/services/), the extra flags (-v, -B, etc) need to be added as a service variable. Below is an example of PostgreSQL Docker image being run as Gitlab Service. You can see that all variables being sent. It looks like they coincide with environment variables and adding an "OTHER" or "EXTRA_FLAGS" environment variable could help. 

There may be instances using Github Actions where this is also useful.

![Screen Shot 2021-05-27 at 10 43 05 AM](https://user-images.githubusercontent.com/29463119/119856997-cb6c0700-bed8-11eb-947e-68b3524c61b5.png)

**Comment by waggledans** [comment]
@raptorsin6  can you take a look? All the flags can be set as env vars, just need to update the docs

**Comment by diemol** [comment]
@waggledans @raptorsin6 
feel free to create a PR and I'll be happy to merge!
