### ISSUE TITLE
Entrypoint: trap SIGTERM and forward SIGINT to sauce connect

### ISSUE THREAD

**Issue by austinpray-mixpanel** [saucelabs/sauce-connect-docker#55]
sauce connect expects a SIGINT for a graceful shutdown: https://docs.saucelabs.com/secure-connections/sauce-connect/proxy-tunnels/#to-stop-a-single-tunnel-kill-signal
Kubernetes sends SIGTERM to pods to signal a graceful shutdown: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace

Will you consider updating the entrypoint to trap SIGTERM and send SIGINT to sauce connect so this container plays nicer with a Kubernetes environment?

**Comment by alexh-sauce** [comment]
@austinpray-mixpanel I think this should actually be a fix to our docs - `SIGTERM` does a graceful shutdown of the SC client.

```bash
<snipped startup>

Sauce Connect is up, you may start your tests.
Stopping client
Will wait for up to 300s for any active jobs using this tunnel to finish.
Note: Press CTRL-C again to shut down immediately.
Note: If you do this, tests that are still running will fail.
Waiting for the connection to terminate...
Connection closed (8).
Goodbye.
```

and in another terminal:

```bash
$ pidof sc
44722
$ kill 44722
$
```

**Comment by austinpray-mixpanel** [comment]
Oh beautiful, I can probably just bypass the entrypoint and be good then. The entrypoint bash script swallows SIGTERM right now.
>Will wait for up to 300s for any active jobs using this tunnel to finish.
Off the top of your head, is there a way to extend this wait period? We've got tests that can run 15+ minutes so those will still get killed during the rollout

**Comment by austinpray-mixpanel** [comment]
Actually, testing things out: it looks like it's happy to wait 20 minutes or more for tunnels to close
![image](https://user-images.githubusercontent.com/71290498/195421550-02a46f43-b301-483e-b0a5-f893eaa16d2c.png)

That's a good thing, just surprising seeing as though it explicitly says it will only wait up to 5 minutes

**Comment by alexh-sauce** [comment]
I'll look into the shutdown issue - maybe we have a bug in how we display the timeout vs the actual behaviour.
Closing this issue for now, I've got a docs PR to clarify the behaviour: https://github.com/saucelabs/sauce-docs/pull/1492

**Comment by austinpray-mixpanel** [comment]
Thank you!
